export const CHART_OF_ACCOUNTS = [
  { code: '1000', name: 'Cash', type: 'asset', subType: 'current asset' },
  { code: '1010', name: 'Bank Account', type: 'asset', subType: 'current asset' },
  { code: '1100', name: 'Accounts Receivable', type: 'asset', subType: 'current asset' },
  { code: '1200', name: 'Prepaid Expenses', type: 'asset', subType: 'current asset' },
  { code: '1500', name: 'Equipment', type: 'asset', subType: 'fixed asset' },
  { code: '1600', name: 'Accumulated Depreciation', type: 'asset', subType: 'contra asset' },
  { code: '2000', name: 'Accounts Payable', type: 'liability', subType: 'current liability' },
  { code: '2100', name: 'Accrued Expenses', type: 'liability', subType: 'current liability' },
  { code: '3000', name: "Owner's Equity", type: 'equity' },
  { code: '3100', name: 'Retained Earnings', type: 'equity' },
  { code: '4000', name: 'Sales Revenue', type: 'income' },
  { code: '4100', name: 'Service Revenue', type: 'income' },
  { code: '5000', name: 'Cost of Goods Sold', type: 'expense' },
  { code: '5100', name: 'Salaries & Wages', type: 'expense' },
  { code: '5200', name: 'Rent Expense', type: 'expense' },
  { code: '5300', name: 'Utilities', type: 'expense' },
  { code: '5400', name: 'Supplies Expense', type: 'expense' },
  { code: '5500', name: 'Depreciation Expense', type: 'expense' },
  { code: '5600', name: 'Miscellaneous Expense', type: 'expense' },
];